"export default function Home() {"
"  return ("
"    <main style={{ minHeight: '100vh', padding: '2rem', backgroundColor: '#f3f4f6' }}>"
"      <h1 style={{ color: 'blue', textAlign: 'center' }}>FOX TESTER ???? ???????!</h1>"
"    </main>"
"  )"
"}"
